# Generated by Django 4.1.4 on 2022-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafoleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.CharField(max_length=200)),
                ('titulos', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=100)),
                ('url_github', models.CharField(max_length=200)),
            ],
        ),
    ]
